2022-05-01T20:52:18.943971+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-05-01T20:52:18.943971+00:00 app[web.1]: return util.import_app(self.app_uri)
2022-05-01T20:52:18.943972+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
2022-05-01T20:52:18.943972+00:00 app[web.1]: mod = importlib.import_module(module)
2022-05-01T20:52:18.943972+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
2022-05-01T20:52:18.943973+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-05-01T20:52:18.943973+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-05-01T20:52:18.943973+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-05-01T20:52:18.943974+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2022-05-01T20:52:18.943974+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-05-01T20:52:18.943974+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-05-01T20:52:18.943975+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-05-01T20:52:18.943975+00:00 app[web.1]: File "/app/app.py", line 1, in <module>
2022-05-01T20:52:18.943975+00:00 app[web.1]: from flask import Flask, request, abort
2022-05-01T20:52:18.943976+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask'
2022-05-01T20:52:18.944029+00:00 app[web.1]: [2022-05-01 20:52:18 +0000] [9] [INFO] Worker exiting (pid: 9)
2022-05-01T20:52:18.973659+00:00 app[web.1]: [2022-05-01 20:52:18 +0000] [10] [INFO] Booting worker with pid: 10
2022-05-01T20:52:18.977068+00:00 app[web.1]: [2022-05-01 20:52:18 +0000] [10] [ERROR] Exception in worker process
2022-05-01T20:52:18.977069+00:00 app[web.1]: Traceback (most recent call last):
2022-05-01T20:52:18.977070+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2022-05-01T20:52:18.977070+00:00 app[web.1]: worker.init_process()
2022-05-01T20:52:18.977071+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2022-05-01T20:52:18.977071+00:00 app[web.1]: self.load_wsgi()
2022-05-01T20:52:18.977071+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2022-05-01T20:52:18.977072+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2022-05-01T20:52:18.977072+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2022-05-01T20:52:18.977072+00:00 app[web.1]: self.callable = self.load()
2022-05-01T20:52:18.977073+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2022-05-01T20:52:18.977073+00:00 app[web.1]: return self.load_wsgiapp()
2022-05-01T20:52:18.977073+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-05-01T20:52:18.977073+00:00 app[web.1]: return util.import_app(self.app_uri)
2022-05-01T20:52:18.977073+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
2022-05-01T20:52:18.977073+00:00 app[web.1]: mod = importlib.import_module(module)
2022-05-01T20:52:18.977074+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
2022-05-01T20:52:18.977074+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-05-01T20:52:18.977074+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-05-01T20:52:18.977075+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-05-01T20:52:18.977075+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2022-05-01T20:52:18.977075+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-05-01T20:52:18.977075+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-05-01T20:52:18.977075+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-05-01T20:52:18.977075+00:00 app[web.1]: File "/app/app.py", line 1, in <module>
2022-05-01T20:52:18.977076+00:00 app[web.1]: from flask import Flask, request, abort
2022-05-01T20:52:18.977076+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask'
2022-05-01T20:52:18.977117+00:00 app[web.1]: [2022-05-01 20:52:18 +0000] [10] [INFO] Worker exiting (pid: 10)
2022-05-01T20:52:19.011439+00:00 app[web.1]: Traceback (most recent call last):
2022-05-01T20:52:19.011445+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 202, in run
2022-05-01T20:52:19.011920+00:00 app[web.1]: self.manage_workers()
2022-05-01T20:52:19.011931+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
2022-05-01T20:52:19.012139+00:00 app[web.1]: self.spawn_workers()
2022-05-01T20:52:19.012150+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 623, in spawn_workers
2022-05-01T20:52:19.012304+00:00 app[web.1]: time.sleep(0.1 * random.random())
2022-05-01T20:52:19.012305+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2022-05-01T20:52:19.012409+00:00 app[web.1]: self.reap_workers()
2022-05-01T20:52:19.012419+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2022-05-01T20:52:19.012568+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2022-05-01T20:52:19.012611+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-05-01T20:52:19.012642+00:00 app[web.1]: 
2022-05-01T20:52:19.012644+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2022-05-01T20:52:19.012644+00:00 app[web.1]: 
2022-05-01T20:52:19.012644+00:00 app[web.1]: Traceback (most recent call last):
2022-05-01T20:52:19.012645+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2022-05-01T20:52:19.012723+00:00 app[web.1]: sys.exit(run())
2022-05-01T20:52:19.012734+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2022-05-01T20:52:19.012831+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2022-05-01T20:52:19.012832+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
2022-05-01T20:52:19.012929+00:00 app[web.1]: super().run()
2022-05-01T20:52:19.012931+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
2022-05-01T20:52:19.013014+00:00 app[web.1]: Arbiter(self).run()
2022-05-01T20:52:19.013025+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 229, in run
2022-05-01T20:52:19.013127+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2022-05-01T20:52:19.013134+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 342, in halt
2022-05-01T20:52:19.013231+00:00 app[web.1]: self.stop()
2022-05-01T20:52:19.013239+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 393, in stop
2022-05-01T20:52:19.013566+00:00 app[web.1]: time.sleep(0.1)
2022-05-01T20:52:19.013574+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2022-05-01T20:52:19.013686+00:00 app[web.1]: self.reap_workers()
2022-05-01T20:52:19.013695+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2022-05-01T20:52:19.013840+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2022-05-01T20:52:19.013869+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-05-01T20:52:19.169721+00:00 heroku[web.1]: Process exited with status 1
2022-05-01T20:52:19.349946+00:00 heroku[web.1]: State changed from starting to crashed
2022-05-01T21:03:33.838110+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=app-line-bot-0501.herokuapp.com request_id=5508215c-a6db-40d3-a33d-c8b21446aa88 fwd="92.238.18.30" dyno= connect= service= status=503 bytes= protocol=https
2022-05-01T21:03:34.152477+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=app-line-bot-0501.herokuapp.com request_id=aacfdb46-36e9-4d06-ad9e-373c99e6c2bc fwd="92.238.18.30" dyno= connect= service= status=503 bytes= protocol=https
2022-05-01T21:07:11.000000+00:00 app[api]: Build started by user apple49755@gmail.com
2022-05-01T21:07:52.175221+00:00 app[api]: Release v4 created by user apple49755@gmail.com
2022-05-01T21:07:52.175221+00:00 app[api]: Deploy 7c78974d by user apple49755@gmail.com
2022-05-01T21:07:53.262331+00:00 heroku[web.1]: State changed from crashed to starting
2022-05-01T21:07:56.796304+00:00 heroku[web.1]: Starting process with command `gunicorn app:app`
2022-05-01T21:07:58.645614+00:00 app[web.1]: [2022-05-01 21:07:58 +0000] [4] [INFO] Starting gunicorn 20.1.0
2022-05-01T21:07:58.645929+00:00 app[web.1]: [2022-05-01 21:07:58 +0000] [4] [INFO] Listening at: http://0.0.0.0:55758 (4)
2022-05-01T21:07:58.645969+00:00 app[web.1]: [2022-05-01 21:07:58 +0000] [4] [INFO] Using worker: sync
2022-05-01T21:07:58.649596+00:00 app[web.1]: [2022-05-01 21:07:58 +0000] [9] [INFO] Booting worker with pid: 9
2022-05-01T21:07:58.730465+00:00 app[web.1]: [2022-05-01 21:07:58 +0000] [10] [INFO] Booting worker with pid: 10
2022-05-01T21:07:59.125643+00:00 heroku[web.1]: State changed from starting to up
2022-05-01T21:08:02.000000+00:00 app[api]: Build succeeded
2022-05-01T21:11:56.563273+00:00 app[web.1]: 10.1.13.101 - - [01/May/2022:21:11:56 +0000] "GET / HTTP/1.1" 404 207 "https://dashboard.heroku.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-01T21:11:56.563536+00:00 heroku[router]: at=info method=GET path="/" host=app-line-bot-0501.herokuapp.com request_id=4f84375b-06ca-4aad-a8b4-323711e4fad7 fwd="92.238.18.30" dyno=web.1 connect=1ms service=3ms status=404 bytes=368 protocol=https
2022-05-01T21:11:56.654614+00:00 app[web.1]: 10.1.13.101 - - [01/May/2022:21:11:56 +0000] "GET /favicon.ico HTTP/1.1" 404 207 "https://app-line-bot-0501.herokuapp.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-01T21:11:56.654630+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=app-line-bot-0501.herokuapp.com request_id=dcbf2993-ba08-4270-a694-ea2ebe91abb3 fwd="92.238.18.30" dyno=web.1 connect=1ms service=2ms status=404 bytes=368 protocol=https
